version: '3.5'

services:
  jupyter-base:
    image: cyb3rward0g/jupyter-base:0.0.7
    container_name: jupyter-base
    environment:
      JUPYTER_TYPE: lab
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
    restart: always
    networks:
      arkana:
        ipv4_address: 172.19.0.200

networks:
  arkana:
    external: true

volumes:
  notebooks:
    driver: local
